
gen_dag: 
  enabled: False
  num_nodes: 5
  edge_prob: 0.5
  edge_weight_range: [-10,10]
  edge_noise_sd_range: [0.001, 2]

load_dag:
  enabled: True
  path: '../../datasets/evaluation'
  dag_name: 'dag_b90ba55a'

exit_after_1: False

gen_dataset:
  enabled: False
  num_points: 1000
  min_source_val: -10
  max_source_val: 10

load_dataset:
  enabled: True
  path: '../../datasets/evaluation'
  dataset_name: 'dag_b90ba55a_dataset_a7918e64'

exit_after_2: True