
gen_dag: 
  ground_truth_dags: 5
  num_nodes: 10
  edge_prob: 0.5
  edge_weight_range: [-10,10]
  edge_noise_sd_range: [0.001, 2]

gen_dataset:
  datasets_per_ground_truth_dag: 5
  num_points: 1000
  min_source_val: -10
  max_source_val: 10

gen_starting_dag:
  starting_dags: 5
  num_nodes: 10
  edge_prob: 0.5
  edge_weight_range: [-10,10]
  edge_noise_sd_range: [0.001, 2]

run_eccs:
  num_steps: 10
  method: 'best_single_edge_change'

run_baseline:
  num_steps: 10
  num_tries: 5





